### ISSUE TITLE
VCF output which conforms GWAS-VCF specification

### ISSUE THREAD

**Issue by ilevantis** [neurogenomics/MungeSumstats#102]
MRC-IEU has proposed a standard GWAS VCF format with specification here with the intention that multiple tools will be able to use this as a standard format: https://github.com/MRCIEU/gwas-vcf-specification

This format is close but not exactly the same as the VCF output from MungeSumstats. It would be a useful addition if MungeSumstats could output VCFs that conform to this standard and could therefore be more interoperable with other tools.

Given that the current output format is already quite close (main difference is column names and how RSID is stored) it would hopefully not be too much work to support.

**Comment by Al-Murphy** [comment]
Hey! Yep I agree this would be useful. We didn't do this in our current approach as we wanted the output column names to be standard across the different output types (e.g. 'SNP' rather than 'RSID'). However, I'll look to add this functionality, controllable with an input parameter in my next dev release - should be available on Github in the next few weeks. I'll update this issue when it is.

**Comment by Al-Murphy** [comment]
This has been added to 1.5.5! You can get it from the dev version of bioconductor (3.16) or install the master branch from Github directly

**Comment by ilevantis** [comment]
Thank you for adding this! I will test it out soon and let you know if I hit any difficulties.
