### ISSUE TITLE
`format_sumstats` cannot differentiate `\t` and `whitespace` when used together

### ISSUE THREAD

**Issue by Lloyd-LiuSiyi** [neurogenomics/MungeSumstats#134]
## 1. Bug description

I was reformatting a GWAS summary statistics for epilepsy whose size was about 400M.  It had 13 columns, the first 11 of which were separated by `\t`.  The last 3 columns were separated by `whitespace`. Here's what it looks like using `sed -n l`:
```shell
$ head -3 ILAE3_focal_HS_final.tbl| sed -n l
CHR \t BP \t MarkerName \t Allele1 \t Allele2 \t Freq1 \t FreqSE \t E\
ffective_N \t Z-score \t P-value \t Direction \t Beta \t SE$
6\t130840091\trs2326918\ta\tg\t0.8211\t0.0334\t4870.18\t0.674\t0.5001\
\t+-? 0.0178176 0.0264356$
7\t145771806\trs6977693\tt\tc\t0.8260\t0.0370\t4870.18\t-0.022\t0.982\
1\t+-? -0.000587991 0.0267269$
```
It seems that `MungeSumstats::format_sumstats` treated the last 3 columns as one. Therefore the output file contained only 11 columns. 
```
Successfully finished preparing sumstats file, preview:
Reading header.
         SNP CHR      BP A1 A2    FRQ  FRQSE    N     Z      P
1: rs6689308   1 1029805  A  G 0.8053 0.0358 4870 1.272 0.2035
2: rs6687776   1 1030565  C  T 0.1940 0.0351 4870 1.419 0.1560
3: rs6678318   1 1030633  G  A 0.1940 0.0351 4870 1.423 0.1547
4: rs9651270   1 1031973  C  T 0.1928 0.0377 4870 1.448 0.1477
                  DIRECTION
1:  ++? 0.0325436 0.0255846
2: --? -0.0363527 0.0256185
3: --? -0.0364551 0.0256185
4: --? -0.0371829 0.0256788
Returning path to saved data.
```

### Expected behaviour   

I was wondering if different delimiters could be detected when they were used together. In this case I wish the `Beta` and `SE` columns could have been identified and also separated by `\t`.

### Code 

(Please add the steps to reproduce the bug here. See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! __This will help us to help you much faster.__)

```R
> library(MungeSumstats)
> MungeSumstats::format_sumstats("ILAE3_focal_HS_final.tbl", ref_genome = "GRCh37", bi_allelic_filter = FALSE, allele_flip_frq = FALSE)
```

### Data
The GWAS summary statistics I used can be downloaded from: https://drive.google.com/file/d/1ZXNfJScM7jRBhERkC8mbElISN5rKTPEB/view?usp=share_link

## 3. Session info

<details>

```R
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8 
[2] LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] GenomeInfoDb_1.34.3 IRanges_2.32.0      S4Vectors_0.36.0   
[4] BiocGenerics_0.44.0 MungeSumstats_1.6.0

```
</details>

**Comment by Al-Murphy** [comment]
Hey! Thanks for bringing this to my attention however, I'm not sure this is something that we should/could correct for. The underlying call to read in data like this sumstats is `data.table::fread()`, see [here](https://github.com/neurogenomics/MungeSumstats/blob/7feb5d53891f4404744c5f498f89968eb04c5ed6/R/read_sumstats.R#L65). The issue is `data.table::fread()` parameter `sep` can't deal with multiple delimiters and for us to manually code in checks for every combination of delimiter would be a big task for (from what I can see) very little reward. I think it would be best for you to just separate out the resulting Direction column in what's returned from MSS into three columns (`data.table::tstrsplit` would be useful for this) and then you can rerun MSS on the result if you need these columns formatted too. Let me know if that approach wouldn't work?

If you do want a solution in MSS, I suggest either reporting an issue with R data.table to allow `data.table::fread()` to deal with multiple delimiters or feel free to make a pull request for MSS with code to do the same (although I won't merge hard-coded solutions).

Thanks,
Alan.

**Comment by Lloyd-LiuSiyi** [comment]
Hi Murphy! Great thanks for replying. I did as you suggested, and `tidyr::separate` seemed to work fine. There is no need to let MSS handle the delimiter problem, so just keep it the way it is.
