### ISSUE TITLE
Error in .start_as_unnamed_integer(start) :    each range must have a start that is <   2^31 and > - 2^31

### ISSUE THREAD

**Issue by 1650783167jyw** [neurogenomics/MungeSumstats#144]
When I ran the function "format_sumstats()", it made an error "Error in .start_as_unnamed_integer(start) :    each range must have a start that is <   2^31 and > - 2^31".
What did it mean?
How can I solve it?
Thank you.

Formatted summary statistics will be saved to ==>  C:\Users\real\AppData\Local\Temp\RtmpecV3QV\file1f8474a93ed4.tsv.gz
Standardising column headers.
First line of summary statistics file: 
CHR	BP	A2	BETA	SE	P	
Summary statistics report:
   - 1,461,904 rows
   - 1,037 genome-wide significant variants (P<5e-8)
   - 23 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking for merged allele column.
Checking A2 is uppercase
There is no SNP column found within the data. It must be inferred from other column information.
Error in .start_as_unnamed_integer(start) : 
  each range must have a start that is <
  2^31 and > - 2^31

**Comment by Al-Murphy** [comment]
Hey! 

Can you provide a small subset ( ideally or the full dataset if this is not possible) so I can debug? It's very hard to pinpoint the issue otherwise. Also can you let me know the version of R and MungeSumstats that you are using?

Cheers,
Alan

**Comment by 1650783167jyw** [comment]
Hi！

The full dataset was too big to upload it all, so I uploaded a part of dataset. The version of R that I am using is version 4.2.1, and the MungeSumatats is version 1.4.5.
[GCST012796(1).csv](https://github.com/neurogenomics/MungeSumstats/files/10777165/GCST012796.1.csv)

Thank you!

**Comment by Al-Murphy** [comment]
So there appears that something odd has gone wrong with your base-pair position column. I read in the data and checked the maximum value and then compared it to the length of the chromosome (chr1):

```
> max(dat$base_pair_location)
[1] 2.24e+14
dat[base_pair_location==2.240000e+14,]
      V1 chromosome base_pair_location effect_allele standard_error p_value      beta
1: 94456          1           2.24e+14             G        0.07876  0.9907 0.0009995
> 249250621-2.240000e+14
[1] -2.239998e+14
```
As you can see, this is far larger than the size of the chromosome which is causing issues with the `GenomicRanges` package (call `GenomicRanges::makeGRangesFromDataFrame`) when we try to infer the SNP RS IDs. Any idea what happened here?

Anyway I've added a check to interpret if the base-pair position column has a possible value i.e. between 1 and the length of the chromosome (based on the reference genome) and the sumstats will run now (note I used Grch38 as the reference genome below since you didn't tell me which your data relates to. You will need to pass it since your data doesn't have a SNP column = RS ID to infer the reference genome. Using the wrong reference genome will give quite wrong results):

```
> frmt_ss <- MungeSumstats::format_sumstats("~/Downloads/gwas.csv",
+                                           ref_genome="GRch38")


******::NOTE::******
 - Formatted results will be saved to `tempdir()` by default.
 - This means all formatted summary stats will be deleted upon ending the R session.
 - To keep formatted summary stats, change `save_path`  ( e.g. `save_path=file.path('./formatted',basename(path))` ),   or make sure to copy files elsewhere after processing  ( e.g. `file.copy(save_path, './formatted/' )`.
 ******************** 

Formatted summary statistics will be saved to ==>  /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T//RtmpEMXBi5/file13def2d084643.tsv.gz
Importing tabular file: ~/Downloads/gwas.csv
Checking for empty columns.
Standardising column headers.
First line of summary statistics file: 
V1	chromosome	base_pair_location	effect_allele	standard_error	p_value	beta	
Summary statistics report:
   - 366,577 rows
   - 1 genome-wide significant variants (P<5e-8)
   - 4 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking for merged allele column.
Checking A2 is uppercase
Checking for incorrect base-pair positions
500 SNPs have been removed as their BP column is not in the range of 1 to the length of the chromosome
Loading SNPlocs data.
There is no SNP column found within the data. It must be inferred from other column information.
Ensuring all SNPs are on the reference genome.
Loading SNPlocs data.
Loading reference genome data.
Preprocessing RSIDs.
Validating RSIDs of 118,091 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 129 seconds.
6,507 SNPs are not on the reference genome. These will be corrected from the reference genome.
Loading SNPlocs data.
Loading SNPlocs data.
Loading reference genome data.
Preprocessing RSIDs.
Validating RSIDs of 118,091 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 131 seconds.
There is no A1 or A2 allele information column found within the data. It must be inferred from  other column information.
One of A1/A2 are missing, allele flipping will be tested
Deriving A1 from reference genome
Checking for correct direction of A1 (reference) and A2 (alternative allele).
There are 30,715 SNPs where A1 doesn't match the reference genome.
These will be flipped with their effect columns.
Checking for missing data.
Checking for duplicate columns.
Checking for duplicate SNPs from SNP ID.
6,507 RSIDs are duplicated in the sumstats file. These duplicates will be removed
Checking for SNPs with duplicated base-pair positions.
INFO column not available. Skipping INFO score filtering step.
Filtering SNPs, ensuring SE>0.
Ensuring all SNPs have N<5 std dev above mean.
Removing 'chr' prefix from CHR.
Making X/Y/MT CHR uppercase.
Checking for bi-allelic SNPs.
16,376 SNPs are non-biallelic. These will be removed.
Warning: When method is an integer, must be >0.
Sorting coordinates with 'data.table'.
Writing in tabular format ==> /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T//RtmpEMXBi5/file13def2d084643.tsv.gz
Summary statistics report:
   - 101,715 rows (27.7% of original 366,577 rows)
   - 101,715 unique variants
   - 1 genome-wide significant variants (P<5e-8)
   - 4 chromosomes
Done munging in 7.707 minutes.
Successfully finished preparing sumstats file, preview:
Reading header.
           SNP CHR     BP A1 A2 V1      SE      P         BETA
1: rs563428896   1 835499  G  G 17 0.07479 0.8201 -0.016857117
2: rs116473820   1 846338  A  A 23 0.08618 0.9580  0.004510155
3: rs375251332   1 846808  A  T 24 0.08110 0.8519 -0.015113638
4:  rs12725862   1 850780  G  C 27 0.06669 0.9181  0.006975614
Returning path to saved data.
```

So you can see this new check removes 500 SNPs with these weird BP values:

`500 SNPs have been removed as their BP column is not in the range of 1 to the length of the chromosome`

This is available in MSS version 1.7.18 or later

**Comment by 1650783167jyw** [comment]
Thank you!!! It is very helpful for me!

However, how did you check if the base-pair position column has a possible value? 
Using `GenomicRanges GenomicRanges::makeGRangesFromDataFrame`?

Thank you!

**Comment by Al-Murphy** [comment]
So that function told me the base-pairs column contained values outside of the range it expected but if you just filter your input dataset like I did above:

`dat[base_pair_location==2.240000e+14,]` you will see the max value which is far too large.

The function `GenomicRanges::makeGRangesFromDataFrame` will just throw an error and not tell you the row that caused it.

Either way, MMS has now been updated to handle this and will throw a warning saying how many SNPs have values larger than the chromosome length

**Comment by 1650783167jyw** [comment]
Thank you very much!!!

**Comment by Al-Murphy** [comment]
Closing this for now as I believe it's completed, feel free to reopen if you have further issues with it.

Cheers,
Alan.
