### ISSUE TITLE
Option to write as VCF

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#18]
Implemented using :

```R
        VariantAnnotation::writeVcf(vr, filename = check_save_out$save_path)

```

**Comment by bschilder** [comment]
Controlled by user with `write_vcf=` flag in `format_sumstats`

**Comment by Al-Murphy** [comment]
@bschilder this is something myself and @NathanSkene discussed, since you are essentially exporting to VCF without any metadata we didn't find it that useful an option (my understanding was that knowing things like stats on the sequencing and info on the patients was a key part of VCF). Do you see a use case for having it in VCF format without this information included?

**Comment by bschilder** [comment]
Fair point, might be worth putting this info back into the header before saving.

The reason i wanted to leave this as an option is because there's certain software that require VCF format. For example, [DeepSEA](https://hb.flatironinstitute.org/deepsea/) is one of the most commonly used deep learning variant effect predictor models because you can easily upload a VCF to their web server.

I don't think we need to provide output formats for every format, but VCF is a big one right up there with tabular data. Exporting to VCF also means we're providing a tool that potentially makes it easier for people to submit their sum stats to databases like Open GWAS.

Ultimately up to you, and i certainly agree about keeping tabular format as the default, but i think there's some substantial benefits, and it's easy enough to do.

**Comment by Al-Murphy** [comment]
Okay let's go for it that sounds like a fair point. Definitely worth documenting and adding a comment to the code to warn that no metadata will be included in th VCF. Thanks for the suggestionsOn 11 Jul 2021 09:47, "Brian M. Schilder" ***@***.***> wrote:
Fair point, might be worth putting this info back into the header before saving.
The reason i wanted to leave this as an option is because there's certain software that require VCF format. For example, DeepSEA is one of the most commonly used deep learning variant effect predictor models because you can easily upload a VCF to their web server.
I don't think we need to provide output formats for every format, but VCF is a big one right up there with tabular data. Exporting to VCF also means we're providing a tool that potentially makes it easier for people to submit their sum stats to databases like Open GWAS.
Ultimately up to you, and i certainly agree about keeping tabular format as the default, but i think there's some substantial benefits, and it's easy enough to do.

**Comment by NathanSkene** [comment]
I'm in favour of Brian's suggestion as well. Maybe we require that
arguments be provided for some meta-data, e.g. which PMID is it associated
with? Which trait? Should increase the user base for the package if we
allow for this & help encourage takeup of VCF.

**Comment by bschilder** [comment]
For datasets imported from Open GWAS via [`import_sumstats`](https://github.com/neurogenomics/MungeSumstats/issues/9), i can easily enough include this info it's accessible via [`find_sumstats`](https://github.com/neurogenomics/MungeSumstats/issues/22)

**Comment by bschilder** [comment]
Opening a new Issue for this here: #25
