### ISSUE TITLE
Error in ids2rowids(ids) : 

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#23]
Input file VCF: 
[https://gwas.mrcieu.ac.uk/files/finn-a-G6_ALZHEIMER/finn-a-G6_ALZHEIMER.vcf.gz](https://gwas.mrcieu.ac.uk/datasets/finn-a-G6_ALZHEIMER/)

![Screenshot 2021-07-10 at 13 13 32](https://user-images.githubusercontent.com/34280215/125162861-19d01f00-e182-11eb-9e81-c6989bfc24cc.png)

**Comment by bschilder** [comment]
Pinpointed to `load_ref_genome_data` in `check_on_ref_genome` step, specifically:

```R
 gr_rsids <- BSgenome::snpsById(x = SNP_LOC_DATA, 
                                 ids = snps, 
                                 genome=genome,
                                 ifnotfound="drop")
```

**Comment by bschilder** [comment]
Checked and all SNPS do indeed start with "rs", so that's not the issue.

Using the old API `snpid` instead of `ids` seems to run, but for an indefinitely long time...

**Comment by bschilder** [comment]
Using `snpid` arg ultimately fails:
![Screenshot 2021-07-11 at 09 29 47](https://user-images.githubusercontent.com/34280215/125188134-9ae2f100-e22a-11eb-9ef6-95d1695a13a3.png)

**Comment by bschilder** [comment]
Tried running this again after integrating the bschilder_dev branch, and get a slightly different error now:
 
![Screenshot 2021-07-20 at 12 07 50](https://user-images.githubusercontent.com/34280215/126314101-f4a97271-bb91-4a90-831c-fac0d87b2c44.png)

**Comment by Al-Murphy** [comment]
The issue is there are some SNPs in the VCF file that don't start with "rs" (see below) so we can't infer what the genome build is as they would all need to be formatted correctly for that.
```
> sumstats_return$sumstats_dt
         CHR        BP         SNP A1 A2      INFO    BETA     SE         LP        AF          P
      1:   1     14717 rs377122907  G  A 0.0007922 -0.4509 0.8894   0.213107 0.0007922 0.61219954
      2:   1     16226 rs755466349 AG  A 0.0117100 -0.1112 0.3016   0.147276   0.01171 0.71240015
      3:   1     17101           .  G  C 0.0170900 -0.1644  0.226   0.330683   0.01709 0.46700013
      4:   1     17181           .  G  C 0.0013130   1.839 0.7884    1.70597  0.001313 0.01968022
      5:   1     17626           .  G  A 0.0147800  0.2163  0.235   0.446845   0.01478 0.35740037
     ---                                                                                         
7721679:   X 155253679 rs782302198  A  G 0.0004649 -1.1232   1.08   0.525201 0.0004649 0.29840012
7721680:   X 155255986 rs143945053  C  A 0.0466600  0.1762 0.0793    1.58004   0.04666 0.02630026
7721681:   X 155258036           .  T  C 0.9963870  0.0063 0.3137 0.00696077  0.996387 0.98410000
7721682:   X 155259147   rs3105275  A  G 0.7603000  0.0586 0.0374   0.931072    0.7603 0.11720010
7721683:   X 155259351 rs181070478  A  G 0.0042100 -0.0345 0.2531  0.0498787   0.00421 0.89149990
```

The first thing to do is to try and infer the reference genome using other columns that have data. We can set up a check around this that will throw an error if too few (I guess 10k/50% which ever is smaller would be enough) SNPs in the dataset have "rs" in their IDs to infer the reference genome.

The second issue becomes apparent when you set the reference genome on calling `import_sumstats`. Then 641,251 SNP IDs are corrected from the reference genome which I guess would be the "." rows above, this is fine. Next though, you get an error when checking that SNPs are on the reference genome, the call to `load_ref_genome_data` causes it,  which is the same error you screenshotted first. So at least we are consistent! 

This issue is caused by some weird rs ids for example:
```
head(sumstats_return$sumstats_dt$SNP[grepl("_",sumstats_return$sumstats_dt$SNP)])
[1] "rs5772025_rs397784053"              "rs56367715_rs397793142"             "rs6143081_rs79212057"              
[4] "rs535071880_rs35755565"             "rs146206790_rs774870800_rs70949530" "rs145470050_rs34767445"  
```

Removing these solves the issue with `load_ref_genome_data`. Also these weird rs IDs are all also present on input so aren't something MungeSumstats creates:
```
> all.equal(sort(sumstats_return$sumstats_dt$SNP[grepl("_",sumstats_return$sumstats_dt$SNP)]),
+             sort(sumstats_return_org$sumstats_dt$SNP[grepl("_",sumstats_return_org$sumstats_dt$SNP)]))
[1] TRUE
```

The fix would be to just remove these when loading the reference genome then if any data is inferred from the reference genome (like the on reference genome check or to impute CHR/BP/A1/A2) these SNPs will be removed. I think this is the best option since we wouldn't know what to do with these SNPs otherwise. This would remove 73928 SNPs.

**Comment by Al-Murphy** [comment]
Added the two above mentioned checks and the file is now running through. Worth noting a good few of the SNPs were filtered out:
```
Summary statistics report:                                                                                                           
   - 1,971,567 rows (25.5% of original 7,721,683 rows)
   - 1,971,506 unique variants
   - 21 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
```
