### ISSUE TITLE
Output results as *.gz for LDSC ready format

### ISSUE THREAD

**Issue by Al-Murphy** [neurogenomics/MungeSumstats#3]

**Comment by Al-Murphy** [comment]
@bschilder might be worth us looking into adding this functionality to your branch, it was asked for from a user. Do you know what exactly is required for this format?

**Comment by bschilder** [comment]
Been a while since i used LDSC but im sure i could figure it out. Will add to my branch (bschilder_dev) once I do.

**Comment by Al-Murphy** [comment]
Great, let me know if I can help with this? I have yet to actually run LDSC myself though!

**Comment by bschilder** [comment]
Info here:
https://github.com/bulik/ldsc/wiki/Summary-Statistics-File-Format 

I think we most things by default except:
- Z
- Guaranteeing N is present 
- Making A1/A2 correspond to effect/other alleles (instead of ref/alt like we currently do).

That said, Kitty was able to run Open GWAS sum stats i just processed with MungeSumstats, but only after running LDSC's `munge_sumstats.py`

**Comment by Al-Murphy** [comment]
Yep so Roxy said a similar thing that after running munge_sumstats.py it was fine. We should probably look at that function? My interpretation was that it just removed unnecessary columns?

**Comment by bschilder** [comment]
Exporting to LDSC format is now supported by setting `format_sumstats(ldsc_format=TRUE, ...)`


New functions to support this are: 

## check_ldsc_format 

https://github.com/neurogenomics/MungeSumstats/blob/bschilder_dev/R/check_ldsc_format.R 

##  check_zscore

https://github.com/neurogenomics/MungeSumstats/blob/bschilder_dev/R/check_zscore.R

**Comment by bschilder** [comment]
Passed `force_new_z` up to `format_sumstats` and set default to FALSE.
