### ISSUE TITLE
Update Bioconductor binaries?

### ISSUE THREAD

**Issue by demodw** [neurogenomics/MungeSumstats#47]
Hi,

It seems the binaries in Bioconductor (https://bioconductor.org/packages/release/bioc/html/MungeSumstats.html) is still v1.0.1. Any chance of pushing a new release? The current guides don't really match up and it seems there's been a lot of bug fixes since then.

Br,
David

**Comment by Al-Murphy** [comment]
Hi David,

Since the recent changes to Mungesumstats has included substantial feature enhancements, the advice from Bioconductor is to release the new version with the next Bioconductor release (3.14) which will happen in Sep/Oct. The advice is to leave pushing to the live version for minor bug fixes which I don't think includes the changes we made. 

I know this is not ideal but until then you can get the latest version of MungeSumstats from github `install_github("neurogenomics/Mungesumstats")` or by installing the dev version of bioconductor where is also available `BiocManager::install(version = "devel")`.

Thanks,
Alan.

**Comment by demodw** [comment]
I see. That makes sense. Works perfectly, but some issues parsing sumstats still remain. I'll open a new issue for that.

Cheers,
David
